INSERT INTO USER (USERNAME, PASSWORD) VALUES ('admin', 'Pa$$w0rd');
INSERT INTO AUTH_USER_GROUP (USERNAME, AUTH_GROUP) VALUES('admin', 'USER');
INSERT INTO AUTH_USER_GROUP (USERNAME, AUTH_GROUP) VALUES('admin', 'ADMIN');

UPDATE USER set password = '$2a$10$HyMNDJUOm5/tqiESg2hGjOkwgj.EXBMZzQEavyPxZrIA0Ab4NoDgK'
WHERE username = 'admin';